### ISSUE TITLE
Coveralls does not show any coverage

### ISSUE THREAD

**Issue by jmramosr** [jmramosr/TravisCppCmakeExample#2]

**Comment by jmramosr** [comment]
It seems there's a problem with coveralls and travis.
The travis log shows that:

> Traceback (most recent call last):
>   File "/home/travis/.local/bin/coveralls", line 8, in <module>
>     sys.exit(run())
>   File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/__init__.py", line 97, in run
>     cov_report = coverage.collect(args)
>   File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/coverage.py", line 458, in collect
>     src_report['coverage'] = parse_gcov_file(args, fobj, gcov_path)
>   File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/coverage.py", line 261, in parse_gcov_file
>     line_num = int(line_num)
> ValueError: invalid literal for int() with base 10: '3-block  0'

**Comment by jmramosr** [comment]
Erased coveralls.
